# Generated by Django 4.0.3 on 2024-01-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCarts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcart',
            name='quantity',
        ),
    ]
