# Generated by Django 4.0.3 on 2024-01-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carParts', '0001_initial'),
        ('users', '0001_initial'),
        ('shoppingCarts', '0002_remove_shopingcart_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopingCart',
            new_name='ShoppingCart',
        ),
    ]
