# Generated by Django 4.0.3 on 2024-01-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shoppingCarts', '0003_rename_shopingcart_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='CarPartID',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='ProductID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
